steps:
  # 1) Install dependencies
  - name: "python:3.9"
    id: "Install dependencies"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip install --upgrade pip
        pip install -r requirements.txt

  # 2) Run tests
  - name: "python:3.9"
    id: "Run tests"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pytest --maxfail=1 --disable-warnings -q tests/

