steps:
  # 1) Install dependencies
  - name: "python:3.9"
    id: "Install dependencies"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip install --upgrade pip
        pip install pytest==7.4.2
        pytest --maxfail=1 --disable-warnings -q tests/
        python train.py

  # 2) Run tests
  # - name: "python:3.9"
  #   id: "Run tests"
  #   entrypoint: "bash"
  #   args:
  #     - "-c"
  #     - |
  #       pytest --maxfail=1 --disable-warnings -q tests/

# Use a custom service account (replace with your actual SA info).
serviceAccount: "projects/YOUR_PROJECT_ID/serviceAccounts/YOUR_SA_NAME@YOUR_PROJECT_ID.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
